#!/usr/bin/env python3
"""Convert a BMP to top-to-bottom RGB565 pixels for AmebaILI9341.drawBitmap."""
# usage: python bmp2hpp.py bitmaps/filename.bmp
# output: bitmaps/filename.hpp

import argparse
import struct
import sys
import re
from pathlib import Path

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument(
    "bmp", nargs="?",
    default=str(Path(__file__).resolve().parent / "bitmaps" /
                "00_neutral_smile_240x320_RGB565.bmp"),
    help="input 16-bit or 24-bit BMP (default: bundled 240x320 RGB565 bitmap)",
)
parser.add_argument("hpp", nargs="?", help="output header (default: input path with .hpp suffix)")
args = parser.parse_args()
BMP_PATH = args.bmp
HPP_PATH = args.hpp or str(Path(BMP_PATH).with_suffix(".hpp"))
array_name = re.sub(r"[^A-Za-z0-9_]", "_", Path(HPP_PATH).stem)

with open(BMP_PATH, "rb") as f:
    data = f.read()

if data[:2] != b"BM":
    sys.exit("Not a valid BMP file")

if len(data) < 54:
    sys.exit("Truncated BMP header")

bf_data_offset = struct.unpack_from("<I", data, 10)[0]
bi_size = struct.unpack_from("<I", data, 14)[0]
if bi_size < 40 or len(data) < 14 + bi_size:
    sys.exit("Unsupported or truncated BMP header")

width = struct.unpack_from("<i", data, 18)[0]
height = struct.unpack_from("<i", data, 22)[0]
bi_bit_count = struct.unpack_from("<H", data, 28)[0]
compression = struct.unpack_from("<I", data, 30)[0]

if bi_bit_count not in (16, 24):
    sys.exit(f"Expected 16-bit or 24-bit BMP, got {bi_bit_count}-bit")
if compression not in (0, 3) or (bi_bit_count == 24 and compression != 0):
    sys.exit(f"Unsupported BMP compression: {compression}")
if width <= 0 or height == 0:
    sys.exit("Invalid BMP dimensions")

minimum_offset = 14 + bi_size
if bi_bit_count == 16:
    # BI_RGB uses RGB555; BI_BITFIELDS supplies explicit channel masks.
    masks = (0x7C00, 0x03E0, 0x001F)
    if compression == 3:
        if bi_size != 40 and bi_size < 52:
            sys.exit("Unsupported BMP bitfield header")
        minimum_offset = max(minimum_offset, 66)
        if len(data) < 66:
            sys.exit("Truncated BMP color masks")
        masks = struct.unpack_from("<III", data, 54)
    channels = []
    used_mask = 0
    for mask in masks:
        if not mask or mask > 0xFFFF or mask & used_mask:
            sys.exit("Invalid BMP color masks")
        shift = (mask & -mask).bit_length() - 1
        maximum = mask >> shift
        if maximum & (maximum + 1):
            sys.exit("Non-contiguous BMP color masks")
        channels.append((mask, shift, maximum))
        used_mask |= mask

top_down = height < 0
height = abs(height)

pixel_data = data[bf_data_offset:]

out = []
bytes_per_pixel = bi_bit_count // 8
row_stride = (width * bytes_per_pixel + 3) // 4 * 4
if bf_data_offset < minimum_offset or len(pixel_data) < row_stride * height:
    sys.exit("Invalid BMP pixel offset or truncated pixel data")

rows = range(height) if top_down else range(height - 1, -1, -1)
for y in rows:
    row_start = y * row_stride
    for x in range(width):
        idx = row_start + x * bytes_per_pixel
        if bi_bit_count == 16:
            pixel = struct.unpack_from("<H", pixel_data, idx)[0]
            r5, g6, b5 = (
                (((pixel & mask) >> shift) * target + maximum // 2) // maximum
                for (mask, shift, maximum), target in zip(channels, (31, 63, 31))
            )
        else:
            b, g, r = pixel_data[idx:idx + 3]
            r5 = r >> 3
            g6 = g >> 2
            b5 = b >> 3
        p16 = (r5 << 11) | (g6 << 5) | b5
        # drawBitmap consumes one unsigned short per pixel, not two byte entries.
        # The display driver handles transmission byte order.
        out.append(p16)

count = len(out)

lines = []
lines.append("/*!")
lines.append("\t@file    " + Path(HPP_PATH).name)
lines.append("\t@author  Generated by bmp2hpp.py")
lines.append("\t@brief   Library header file for test bitmap data, holds bitmap data.")
lines.append("\t@note    NOT part of core library only used for holding test data,")
lines.append("\t\t\t can be omitted in project use or port.")
lines.append("\t@details bitmaps in file")
lines.append(f"\t\t        -#  {array_name}    : 16 bit color 565,  "
             f"{count} pixels, {count * 2} bytes ({width}x{height})")
lines.append("*/")
lines.append("")
lines.append("#pragma once")
lines.append("")
lines.append("/// @cond")
lines.append("")
lines.append(f"// array size is {count} pixels ({width}x{height}), {count * 2} bytes")
lines.append(f"// BMP pixel data offset {bf_data_offset}")
lines.append("// RGB 565 16 bit color")
lines.append("")
lines.append(f"const unsigned short {array_name}[{count}] PROGMEM = {{")
for start in range(0, count, 8):
    lines.append("    " + ", ".join(f"0x{pixel:04X}" for pixel in out[start:start + 8]) + ",")
lines.append("};")
lines.append("")

with open(HPP_PATH, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

print(f"Wrote {HPP_PATH} ({width}x{height}, {count} pixels, {count * 2} bytes), 16-bit RGB565 HPP")
