/* =====================================================================
 * knowledge.js — 虛擬人的知識庫（檢索 / Retrieval 來源）
 * 這個 demo 版的內容＝「這個元件本身的使用教學」，她會自己當自己的說明書。
 * 換領域只要改這個檔；接上 LLM 時，也是把這裡的內容當「依據」餵進去。
 * 每筆：q=代表問題、kw=關鍵字(增加命中率)、a=回答(盡量短，TTS 唸起來順)
 * ref（選填）= 對應本機素材圖片路徑（相對 assets/，非外部 URL）
 * ===================================================================== */
window.KB = [
  { q: '這是什麼',         kw: '你是誰 這是什麼 介紹 自我介紹 什麼東西',
    a: '我是一個AI小助教, 你可以參考教材提出問題。' },
  { q: '學習目標',   kw: '目標 目的 重點',
    a: '掌握多模態生成式 AI應用，整合 TTS, STT, LLM, 並佈署於機器人系統, 及實現VLA之機器人控制' },
  { q: '教學特色',   kw: '特色 設備 教具',
    a: '採用NVIDIA Jetson Orin Nano Super開發板，實際佈署 Gemma-4 模型，教材網頁AI化' },
  { q: '課程亮點',   kw: '亮點 教學平台 Gemma4',
    a: '使用 Gemma-4 模型，採用Orin-Nano-Super及AMB82 mini等開發板，實作AI代理，助理及機器人動作控制' },
  { q: '內容大綱',   kw: '大綱 章節 教材 內容',
    a: '開發者套件介紹，本機語音合成，本機語音識別，本機語言模型，AI代理開發平台，AI助理應用實作，VLA機器人實作' },
  { q: '開發者套件',   kw: '硬體 硬件 套件 開發板 介紹',
    a: '本課程採用NVIDIA JETSON ORIN NANO Super開發板，請參考教材第一章!' },
  { q: '語音怎麼用',         kw: '語音 說話 麥克風 怎麼講 對話 講話 聽',
    a: '點下面的麥克風按鈕、允許權限，就能直接對我說話。我會用語音回答你，嘴巴也會跟著動。' },
  { q: '麥克風怎麼用（步驟）', kw: '麥克風 怎麼開麥 步驟 收音 不能說話 沒反應 權限 允許 聆聽中 開麥克風 怎麼跟你講',
    a: '第一步點下面綠色的麥克風鈕；第二步瀏覽器跳出權限就按「允許」；看到「聆聽中」三個字就直接開口說，我會把你的話顯示出來再回答。' },
  { q: '可以用打字的嗎',     kw: '打字 輸入 鍵盤 文字 輸入框 不方便說話 不能說話 沒有麥克風 不想開麥 打中文',
    a: '可以！下面有輸入框，打完字按 Enter 或旁邊的送出鍵，我一樣會用語音回答你、嘴巴也會跟著動。不方便開口的場合就用打的吧。' },
  { q: '我可以說什麼',       kw: '可以說什麼 說什麼 可以問什麼 問什麼 講什麼 範例 例子 指令 有哪些 不知道問什麼 該說什麼 詞彙',
    a: '你可以直接對我說：「學習目標」「教學特色」「內容大綱」「怎麼靜音」「調語速」這些，我就會回答你。想到什麼直接問也行！' },
  { q: 'AI 大腦是什麼',      kw: '大腦 ai 腦袋 llm 聰明 模型 思考 webllm',
    a: '點腦袋按鈕會在你的瀏覽器裡載入一個小型 AI 模型，讓我能更自然地聊天、回答知識庫沒有的問題。第一次要下載約 1GB。' },
  { q: '怎麼改我的回答內容',  kw: '改內容 知識庫 faq 自訂回答 換內容 knowledge 資料',
    a: '改 knowledge.js，或用 data-knowledge 指向你自己的 JSON。每筆寫「問題、關鍵字、回答」三欄就行。' },
  { q: '支援哪些瀏覽器',     kw: '瀏覽器 chrome 支援 相容 手機 safari edge',
    a: '建議用 Chrome 桌機，語音辨識和 AI 大腦在 Chromium 上最完整。其他瀏覽器基本功能也能跑。' },
  { q: '這是開源的嗎',       kw: '開源 授權 license 免費 商用 github 版權',
    a: '是的，採 MIT 授權，可自由使用修改。但內建的 Live2D 範例角色是 Live2D 的範例素材，正式上線請換成你自有的角色。' },
  { q: '對嘴怎麼做到的',     kw: '對嘴 嘴巴 嘴型 lipsync 同步 嘴',
    a: '神經語音時我會分析真實音量來開合嘴巴，瀏覽器語音時則用節奏模擬，所以講話時嘴型會跟著動。' },
  { q: '怎麼讓她安靜',       kw: '靜音 安靜 關掉聲音 停 不要講 閉嘴 mute',
    a: '點喇叭按鈕可以靜音，會立刻停止正在播放的語音。再點一次恢復。' },
  { q: '收起來',             kw: '收起 關閉 隱藏 縮小 不要顯示 收掉 x',
    a: '點右下角的叉叉就會把我收成一個小泡泡，需要時再點泡泡展開。' },
  { q: '可以調語速嗎',       kw: '語速 速度 講太快 講太慢 快慢 調速',
    a: '點速度按鈕可以循環切換語速，從慢到快有幾段可以選。' },
  { q: '打招呼',             kw: '你好 哈囉 嗨 hello hi 在嗎 哈嘍',
    a: '哈囉！我是AI小助教, 對教材有疑問都可以問我。' },
  { q: '道謝道別',           kw: '謝謝 感謝 感恩 掰掰 再見 bye',
    a: '不客氣！把我裝上你的網站玩玩看吧，有需要再叫我～' },
  { q: '有陪伴模式嗎',       kw: '陪伴 模式 companion 連續 對話 聊天 陪聊 mode',
    a: '有喔！在 embed.js 加 data-mode 等於 companion 就變陪伴型：點一下 💬 開始連續對話，我講完會自動繼續聽，還會記得你的名字跟聊過的話。' },
  { q: '你會記得我嗎',       kw: '記得 記憶 名字 記住 忘記 隱私 存哪',
    a: '陪伴模式下會！名字和最近的對話存在你自己瀏覽器的 localStorage，不會上傳到任何伺服器；想清掉就跟我說「忘記我」。' },
  { q: '開發者套件',  kw: '第一章 第一節 開發者套件 kit Jetson Orin Nano Webcam 硬體安裝 開機',
    a: '選用 NVIDIA Jetson Orin Nano Super 套件。含SSD、webcam及BT頭盔眼鏡，並可透過HDMI螢幕操作。JetPack作業環境則可於官網查詢。' },
  { q: '語音合成',    kw: '第二章 第二節 語音合成 TTS text-to-speech KOKORO edge-tts kokoro 本機發音 soundfile ffmpeg voice 口音 語言',
    a: 'TTS為Text-To-Speech之縮寫，選用 Kokoro-2412 為預設TTS，可於專案資料夾下載。使用範例：python -m tts "Hello!" -o output.mp3 支援英文、日文及中文口音，詳細說明請參閱教材' },
  { q: '語音辨識',    kw: '第三章 第三節 語音辨識 語音識別 STT speech-to-text sherpa-ai whisper openai-ai onnx 偵測',
    a: 'STT為Speech-To-Text之縮寫；以whisper為例，透過本機端開源模型實現語音到文字轉換。Sherpal-AI可支援多語言即時串流處理。詳見教材說明。' },
  { q: '語言模型',    kw: '第四章 第四節 語言模型 LLM ollama OpenCode MCP server open-ai gemma 本地語言模型 jetson 容器 docker container 本機',
    a: '透過 Ollamac 或 Docker 在本機建立 LLM 服務。以 Unsloth-Gemma 為例：ollamac serve unsloth/gemma-4-E2B-it-GGUF。Open Code MCP 支援 Ollama 協議；請參閱教材完整步驟。' },
  { q: 'OpenCode',    kw: '第五章 第五節 opencode open-code MCP provider n8n agent web_search 工具程式 自動化',
    a: 'Open Code為一個開放源碼的AI協同工具集，其透過MCP Server連接Ameba Pro 2硬體及N8N網頁搜尋能力。使用方式可參見官方文件說明。' },
  { q: 'AI 助理', kw: '第六章 第六節 助理 Assistant vtuber open-llm-vtuber Open_llm_Llama-Gemma chatbot ai-avatar live2d jarvis assistant 虛擬人 語音助理 鋼鐵人 配音',
    a: 'Open-LLM-vTuber為開源的LLM 語音模擬工具。可整合llama.cpp server及Gemma-4 (E2B-it)模型，支援Live2D角色驅動及多媒體播放功能；其餘請參閱教材第六章。' },
  { q: 'Gemma-4-VLA',      kw: '第七章 第七節 VLA VLM agent gemma-4 vision-vla robot 機器人 動作控制',
    a: '採用 Google Gemma-4 多模態模型，結合本地STT(Parakeet)及語音系統(Kokoro TTS)，並透過llama.cpp Server部署本機LLM服務；完整流程請參閱教材第七章。' }
];
